---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:
    - name: Install Openjdk
      yum:
        name: java-17-amazon-corretto.x86_64
        state: present
    - name: Download the Jenkins Repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Import Jenkins GPG Key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
    
    - name: Download EPEL RPM
      get_url:
      url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      dest: /tmp/epel-release-latest-7.noarch.rpm
       
    - name: Install Epel Release
      yum:
        name: /tmp/epel-release-latest-7.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
    - name: Start Jenkins
      service:
        name: jenkins
        state: started
    - name: enable Jenkins
      systemd:
        name: jenkins
        enabled: true
    - name: Wait for Jenkins to be available
      wait_for:
        port: 8080
        delay: 30
        timeout: 300

    - name: Get the Admin Password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkinspass
      changed_when: false
    - name: print jenkins password
      debug:
        var: jenkinspass.stdout